# Generated by Django 5.1.7 on 2025-03-24 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=100)),
                ('broj', models.IntegerField()),
                ('telefon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('vid', models.CharField(choices=[('HR', 'Hrana'), ('PI', 'Pijalok'), ('PK', 'Kozmetika'), ('PP', 'Pekara'), ('HI', 'Higiena')], max_length=2)),
                ('domasen', models.BooleanField()),
                ('kod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('broj_na_marketi', models.IntegerField()),
                ('datum_na_otvaranje', models.DateField()),
                ('rabotno_vreme_od', models.TimeField()),
                ('rabotno_vreme_do', models.TimeField()),
                ('kontakt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.kontakt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prozivod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.proizvod')),
            ],
        ),
        migrations.CreateModel(
            name='MarketProizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.market')),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.proizvod')),
            ],
        ),
        migrations.CreateModel(
            name='Vrabotena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('EMBG', models.IntegerField()),
                ('plata', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketVraboten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.market')),
                ('Vrabotena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.vrabotena')),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='vraboten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.vrabotena'),
        ),
    ]
