# Generated by Django 5.1.7 on 2025-03-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrabotena',
            name='markett',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarketApp.market'),
        ),
        migrations.DeleteModel(
            name='MarketVraboten',
        ),
    ]
