# Generated by Django 5.1.7 on 2025-03-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0002_vrabotena_markett_delete_marketvraboten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrabotena',
            name='markett',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarketApp.market'),
        ),
    ]
