# Generated by Django 5.1.7 on 2025-03-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0004_remove_market_vraboten_alter_vrabotena_markett'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketVraboten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vrabotena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.vrabotena')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.market')),
            ],
        ),
    ]
