# Generated by Django 5.1.7 on 2025-03-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0005_marketvraboten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrabotena',
            name='markett',
        ),
        migrations.AddField(
            model_name='market',
            name='vraboten',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarketApp.vrabotena'),
        ),
    ]
